"""The character sites' review redirects.

The back page of every workbook carries a QR to https://<site>/r/<catalog>.
Amazon's review page needs the ASIN, which only exists once the book is live,
so the SITE keeps the map (Cloudflare Pages `_redirects`): a known ASIN goes
to the book's review page, everything else to the site's Books section.
Regenerated on every autopilot day and deployed when it changed.
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

from ..database import list_books

SITES = {
    "princess-the-unicorn": {"src": Path.home() / "Desktop/CATALOG ENGINE/princesstheunicorn-site", "mirror": Path.home() / ".scrpt/web/princesstheunicorn", "project": "princesstheunicorn"},
    "freddie-the-farmer": {"src": Path.home() / "Desktop/CATALOG ENGINE/freddiethefarmer-site", "mirror": Path.home() / ".scrpt/web/freddiethefarmer", "project": "freddiethefarmer"},
    "rex-the-dinosaur": {"src": Path.home() / "Projects/rexthedinosaur-site", "mirror": None, "project": "rexthedinosaur"},
}


def _asin(d: dict) -> str:
    return ((d.get("publishing") or {}).get("asin") or (d.get("kdp") or {}).get("asin") or "").strip()


def render(slug: str) -> str:
    lines = ["# review links from the back page of every book — generated by SCRPT, do not edit"]
    for b in list_books(per_page=2000).get("books", []):
        d = b.get("data") or {}
        if b.get("status") in ("cancelled", "deleted", "archived"):
            continue
        if ((d.get("workbook") or {}).get("universe") or d.get("universe")) != slug:
            continue
        asin = _asin(d)
        if asin:
            lines.append(f"/r/{b['catalog_number'].lower()}  https://www.amazon.com/review/create-review?asin={asin}  302")
    lines.append("/r/*  /#books  302")
    return "\n".join(lines) + "\n"


def _writable(path: Path) -> bool:
    """The engine (a LaunchAgent) has no Desktop access under macOS privacy
    rules — PermissionError on the iCloud source copies, 2026-09-13."""
    try:
        return path.exists() and os.access(path, os.W_OK) and bool(list(path.iterdir()) or True)
    except PermissionError:
        return False


def _roots(site: dict) -> list:
    """Every copy the redirects file should land in: the source when the
    engine may touch it, and the serving mirror always."""
    out = []
    if _writable(site["src"]):
        out.append(site["src"])
    if site.get("mirror") and site["mirror"].exists():
        out.append(site["mirror"])
    return out


def write_all() -> dict:
    changed = {}
    for slug, site in SITES.items():
        text = render(slug)
        for root in _roots(site):
            f = root / "_redirects"
            try:
                old = f.read_text() if f.exists() else ""
                if text != old:
                    f.write_text(text); changed[slug] = sum(1 for l in text.splitlines() if l.startswith("/r/sc-"))
            except PermissionError:
                continue
    return changed


def deploy(slug: str) -> str:
    site = SITES[slug]; src = site["src"]; where = site["mirror"] or src
    cmd = ""
    if site["mirror"] and _writable(src):     # sync only when the source is reachable; the mirror deploys on its own otherwise
        cmd += f'rsync -a --delete "{src}/" "{where}/" && '
    cmd += f'cd "{where}" && . ~/.nvm/nvm.sh >/dev/null 2>&1; nvm use 20 >/dev/null 2>&1; npx wrangler pages deploy . --project-name={site["project"]} --branch=main --commit-dirty=true 2>&1 | tail -2'
    r = subprocess.run(["/bin/zsh", "-lc", cmd], capture_output=True, text=True, timeout=600)
    return (r.stdout or r.stderr)[-300:]


def sync_and_deploy() -> dict:
    changed = write_all(); out = {}
    for slug in changed:
        out[slug] = deploy(slug)
    return {"changed": changed, "deployed": out}
